name: Parallel Jobs Cypress Tests
on: [push]
jobs:

  cypress-run-1:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v3

      - name: Cypress run ğŸš€
        uses: cypress-io/github-action@v4
        with:
          command: npm run run-1

  cypress-run-2:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v3

      - name: Cypress run ğŸš€
        uses: cypress-io/github-action@v4
        with:
          command: npm run run-2

  cypress-run-3:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v3

      - name: Cypress run ğŸš€
        uses: cypress-io/github-action@v4
        with:
          command: npm run run-3
